name: Build JSON/PDF URL index

on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - '**.json'
      - '**.pdf'
      - '.github/workflows/list-json-pdf.yml'
  workflow_dispatch: {} 

permissions:
  contents: write

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate URL list (path, blob URL, raw URL)
        shell: bash
        run: |
          set -euo pipefail
          REF="${GITHUB_SHA}"
          REPO="${GITHUB_REPOSITORY}"
          OUT_DIR="docs"
          OUT_TSV="${OUT_DIR}/json-pdf-urls.tsv"
          mkdir -p "$OUT_DIR"
          : > "$OUT_TSV"

          while IFS= read -r -d '' f; do
            rel="${f#./}"
            blob="https://github.com/${REPO}/blob/${REF}/${rel}"
            raw="https://raw.githubusercontent.com/${REPO}/${REF}/${rel}"
            printf "%s\t%s\t%s\n" "$rel" "$blob" "$raw" >> "$OUT_TSV"
          done < <(find . -type f \( -iname '*.json' -o -iname '*.pdf' \) -print0)

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          if git diff --quiet -- docs/json-pdf-urls.tsv; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/json-pdf-urls.tsv
          git commit -m "chore(ci): update JSON/PDF URL index [skip ci]"
          git push
