name: Validate & Format JSON

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install tools
        run: |
          npm install -g ajv-cli@5 prettier@3
      - name: Prettier - check formatting
        run: |
          prettier -c "**/*.json" || (echo "::warning::Formatting issues detected. Running --write"; prettier -w "**/*.json")
